2nd task
js-tasks-ru/js-20220729_daria-zakirova pull request #2
Opened 2022-08-15 17:25 UTC by daria-z

2022-08-15 17:26 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-08-16 13:46 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    newArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-08-16 13:46 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let fieldsArray = [...fields];
`const`

2022-08-16 13:46 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let newObj = Object.fromEntries(
`const`

2022-08-16 13:47 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    fieldsArray.filter((key) => key in obj).map((key) => [key, obj[key]])
подумайте в чем разница между проверкой `key in obj` и `obj[key]`

2022-08-16 13:47 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let fieldsArray = [...fields];
`const`

2022-08-16 13:48 UTC, dosandk requested changes
В решении sortStrings нужно избавиться от `reverse`

2022-08-23 10:09 UTC, daria-z commented on 02-javascript-data-types/2-pick/index.js
> +    fieldsArray.filter((key) => key in obj).map((key) => [key, obj[key]])
первое проверяет есть ли ключ в объекте, а второе есть ли значение ключей?

2022-08-23 10:13 UTC, daria-z commented on 02-javascript-data-types/1-sort-strings/index.js
> +    newArr.reverse();
reverse хуже тем, что сначала сортирует в прямом порядке, а потом переворачивает, а хорошо бы стразу сортировать как нужно?

2022-08-23 11:22 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-08-23 11:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-08-23 13:06 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>    if (param === "asc") {
👍 good

2022-08-23 13:07 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      a.localeCompare(b, ["ru", "en"], { caseFirst: "upper" })
было бы неплохо избавиться от дубликатов кода, строки 9-11 и 15-17 идентичны за исключением порядка аргументов

2022-08-23 13:08 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    fieldsArray.filter((key) => key in obj).map((key) => [key, obj[key]])
@daria-z да абсолютно верно, поэтому для такого случая:
```
const obj = {
  color: undefined
};

if ('color' in obj) // true
if (obj.color) // false
```

2022-08-23 13:08 UTC, dosandk approved these changes
good 👍

2022-08-23 13:09 UTC, merged

2022-08-23 13:58 UTC, daria-z commented on 02-javascript-data-types/1-sort-strings/index.js
> +      a.localeCompare(b, ["ru", "en"], { caseFirst: "upper" })
да, я понимаю. Так еще и не очевидно чем они отличны, но потом посмотрела что это решение как в лекции и не стала просто копировать